configuration:
  healthcheck:
    script: no-config-script-app-hc.sh
    timeout: 420
  start:
    script: no-config-script-app-cm-command.sh
source:
  image:
    ami:
    - id: ami-940cdceb
      region: ap-northeast-1
      username: ubuntu
    - id: ami-467acf28
      region: ap-northeast-2
      username: ubuntu
    - id: ami-188fba77
      region: ap-south-1
      username: ubuntu
    - id: ami-51a7aa2d
      region: ap-southeast-1
      username: ubuntu
    - id: ami-47c21a25
      region: ap-southeast-2
      username: ubuntu
    - id: ami-db9e1cbf
      region: ca-central-1
      username: ubuntu
    - id: ami-de8fb135
      region: eu-central-1
      username: ubuntu
    - id: ami-f90a4880
      region: eu-west-1
      username: ubuntu
    - id: ami-f4f21593
      region: eu-west-2
      username: ubuntu
    - id: ami-20ee5e5d
      region: eu-west-3
      username: ubuntu
    - id: ami-8eecc9e2
      region: sa-east-1
      username: ubuntu
    - id: ami-759bc50a
      region: us-east-1
      username: ubuntu
    - id: ami-5e8bb23b
      region: us-east-2
      username: ubuntu
    - id: ami-925144f2
      region: us-west-1
      username: ubuntu
    - id: ami-ba602bc2
      region: us-west-2
      username: ubuntu
  os_type: linux
infrastructure:
  connectivity:
    internal:
    - port_info:
        port: 3000
        path: ''
  compute:
    spec:
      aws:
        instance_type: $INSTANCETYPE
inputs:
- INSTANCETYPE: t2.micro,t3.micro,t3.small,t2.small
kind: application
spec_version: 1
debugging:
  connection_protocol: SSH
